### ISSUE TITLE
We should consider making the timestamp field a DateTime, and the serializer can handle the conversion to ISO. 

### ISSUE THREAD

**Issue by mrf460** [pnxtech/Hydra4Net-Development#4]
The JsonSerializeer may serialize it to iso by default, but if not we can write our own converter.  I will investigate

**Comment by cjus** [comment]
That seems like a good idea to me.

**Comment by cjus** [comment]
Added to e7855f6fd2e3d73e0a92895273c05dfe3d199fe2 and pushed to NuGet in version 0.0.10 https://www.nuget.org/packages?q=hydra4net
