### ISSUE TITLE
HydraConfigObject could be simplified

### ISSUE THREAD

**Issue by mrf460** [pnxtech/Hydra4Net-Development#9]
I am thinking that the HydraConfigObject does not need a top-level class.  if the properties of HydraRoot were in the HydraConfigObject. This would allow users to simplify their json config like so:

## Old
```json
{
  "HydraConfig": {
    "Hydra": {
      ......
    }
  }
}
```

## New
```json
{
    "Hydra": {
      ......
    }
}
```

This would obviously cause consumers to need to potentially update their load logic, but I can update the default IConfiguration extension method to look at this new level. Let me know your thoughts or if there is some reason why this wouldn't work.

**Comment by cjus** [comment]
The new approach is consistent with hydra usage across platforms.  Glad we're doing this!

**Comment by cjus** [comment]
Addressed by @mrf460 in https://github.com/pnxtech/Hydra4Net-Development/commit/a74ca33fa1737be9f6ea5948e3ff8a68245d06dd
